# Generated by Django 2.1.15 on 2020-02-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Liked_artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=1)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Liked_genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=1)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Liked_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.Artist')),
                ('genres', models.ManyToManyField(to='playback.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='liked_track',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.Track'),
        ),
        migrations.AddField(
            model_name='liked_track',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.User'),
        ),
        migrations.AddField(
            model_name='liked_genre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.User'),
        ),
        migrations.AddField(
            model_name='liked_artist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playback.User'),
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='playback.Genre'),
        ),
    ]
